aziendaconfig.path=/etc/azienda_config.properties

db.uri=
db.username=
db.password=
db.driver=org.postgresql.Driver
db.encryptionkey=
jwtgenerator.keystore.password=
internauta.jwt.secret=

parameters_service.uri=

ambiente=test

azienda=
regione=